<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.jline</groupId>
  <artifactId>jline</artifactId>
  <version>3.26.3</version>
  <name>JLine Bundle</name>
  <description>JLine</description>
  <url>https://github.com/jline/jline3/jline</url>
  <licenses>
    <license>
      <name>The BSD License</name>
      <url>https://opensource.org/licenses/BSD-3-Clause</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>gnodet</id>
      <name>Guillaume Nodet</name>
      <email>gnodet@gmail.com</email>
      <roles>
        <role>Developer</role>
      </roles>
    </developer>
  </developers>
  <mailingLists>
    <mailingList>
      <name>jline-users</name>
      <subscribe>https://groups.google.com/group/jline-users</subscribe>
      <unsubscribe>mailto:jline-users+unsubscribe@googlegroups.com</unsubscribe>
      <post>mailto:jline-users@googlegroups.com</post>
      <archive>https://groups.google.com/group/jline-users</archive>
    </mailingList>
  </mailingLists>
  <scm>
    <connection>scm:git:https://github.com/jline/jline3.git/jline</connection>
    <developerConnection>scm:git:https://github.com/jline/jline3.git/jline</developerConnection>
    <tag>jline-parent-3.26.3</tag>
    <url>http://github.com/jline/jline3/jline</url>
  </scm>
  <issueManagement>
    <system>github</system>
    <url>https://github.com/jline/jline3/issues</url>
  </issueManagement>
  <ciManagement>
    <system>travis</system>
    <url>https://travis-ci.org/jline/jline3</url>
  </ciManagement>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-native</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-terminal</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-terminal-ffm</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-terminal-jansi</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-terminal-jni</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-terminal-jna</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-reader</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-builtins</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-remote-ssh</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-remote-telnet</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-style</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-groovy</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jline-console</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jansi-core</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.jline</groupId>
        <artifactId>jansi</artifactId>
        <version>3.26.3</version>
      </dependency>
      <dependency>
        <groupId>org.fusesource.jansi</groupId>
        <artifactId>jansi</artifactId>
        <version>2.4.1</version>
      </dependency>
      <dependency>
        <groupId>net.java.dev.jna</groupId>
        <artifactId>jna</artifactId>
        <version>5.14.0</version>
      </dependency>
      <dependency>
        <groupId>com.googlecode.juniversalchardet</groupId>
        <artifactId>juniversalchardet</artifactId>
        <version>1.0.3</version>
      </dependency>
      <dependency>
        <groupId>org.apache.sshd</groupId>
        <artifactId>sshd-common</artifactId>
        <version>2.13.1</version>
      </dependency>
      <dependency>
        <groupId>org.apache.sshd</groupId>
        <artifactId>sshd-core</artifactId>
        <version>2.13.1</version>
      </dependency>
      <dependency>
        <groupId>org.apache.sshd</groupId>
        <artifactId>sshd-scp</artifactId>
        <version>2.13.1</version>
      </dependency>
      <dependency>
        <groupId>org.apache.sshd</groupId>
        <artifactId>sshd-sftp</artifactId>
        <version>2.13.1</version>
      </dependency>
      <dependency>
        <groupId>org.apache.felix</groupId>
        <artifactId>org.apache.felix.gogo.runtime</artifactId>
        <version>1.1.6</version>
      </dependency>
      <dependency>
        <groupId>org.apache.felix</groupId>
        <artifactId>org.apache.felix.gogo.jline</artifactId>
        <version>1.1.8</version>
      </dependency>
      <dependency>
        <groupId>org.apache.groovy</groupId>
        <artifactId>groovy</artifactId>
        <version>4.0.22</version>
      </dependency>
      <dependency>
        <groupId>org.apache.groovy</groupId>
        <artifactId>groovy-json</artifactId>
        <version>4.0.22</version>
      </dependency>
      <dependency>
        <groupId>org.apache.groovy</groupId>
        <artifactId>groovy-console</artifactId>
        <version>4.0.22</version>
      </dependency>
      <dependency>
        <groupId>org.graalvm.sdk</groupId>
        <artifactId>graal-sdk</artifactId>
        <version>24.0.2</version>
      </dependency>
      <dependency>
        <groupId>org.apache.ivy</groupId>
        <artifactId>ivy</artifactId>
        <version>2.5.2</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.13</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-jdk14</artifactId>
        <version>2.0.13</version>
      </dependency>
      <dependency>
        <groupId>org.easymock</groupId>
        <artifactId>easymock</artifactId>
        <version>5.3.0</version>
      </dependency>
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <version>5.10.3</version>
      </dependency>
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-params</artifactId>
        <version>5.10.3</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>com.google.code.findbugs</groupId>
        <artifactId>jsr305</artifactId>
        <version>3.0.2</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.fusesource.jansi</groupId>
      <artifactId>jansi</artifactId>
      <version>2.4.1</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna</artifactId>
      <version>5.14.0</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>com.googlecode.juniversalchardet</groupId>
      <artifactId>juniversalchardet</artifactId>
      <version>1.0.3</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.apache.sshd</groupId>
      <artifactId>sshd-core</artifactId>
      <version>2.13.1</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.apache.sshd</groupId>
      <artifactId>sshd-scp</artifactId>
      <version>2.13.1</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.apache.sshd</groupId>
      <artifactId>sshd-sftp</artifactId>
      <version>2.13.1</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
      <version>3.0.2</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-terminal</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-terminal-jni</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-terminal-jansi</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-terminal-jna</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-terminal-ffm</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-reader</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-builtins</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-console</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-remote-ssh</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-remote-telnet</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline-style</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>apache-snapshots</id>
      <name>Apache Snapshots</name>
      <url>https://repository.apache.org/content/groups/snapshots</url>
    </repository>
  </repositories>
</project>
